/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Imagem;
import transformers.EscalaCinzaTransformer;
import transformers.FiltraCanaisTransformer;
import transformers.InverteCoresTransformer;

/**
 *
 * @author 0186779
 */
public class Tela extends javax.swing.JFrame {

    private Imagem imgEntrada = null;
    private Imagem imgTransformada = null;
    
    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        labelImgEntrada = new javax.swing.JLabel();
        verImgInfo = new javax.swing.JButton();
        labelImgSaida = new javax.swing.JLabel();
        btnTrocarImgs = new javax.swing.JButton();
        comboEfeito = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnAplicarEfeito = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbCanalBlue = new javax.swing.JCheckBox();
        cbCanalRed = new javax.swing.JCheckBox();
        cbCanalGreen = new javax.swing.JCheckBox();
        btnAplicarCanais = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnCarregarImagem = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ivo Fritsch - PDI");

        labelImgEntrada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        verImgInfo.setText("Ver informações da imagem de saída");
        verImgInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verImgInfoActionPerformed(evt);
            }
        });

        btnTrocarImgs.setText("<html>&lt;-<br />-&gt;</html>");
        btnTrocarImgs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrocarImgsActionPerformed(evt);
            }
        });

        comboEfeito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ECZ - Escala de cinza", "ICR - Inverte cores da imagem" }));

        jLabel1.setText("Aplicar efeito:");

        btnAplicarEfeito.setText("Aplicar efeito ->");
        btnAplicarEfeito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarEfeitoActionPerformed(evt);
            }
        });

        jLabel2.setText("Selecionar canais:");

        cbCanalBlue.setSelected(true);
        cbCanalBlue.setText("Azul (B)");

        cbCanalRed.setSelected(true);
        cbCanalRed.setText("Vermelho (R)");

        cbCanalGreen.setSelected(true);
        cbCanalGreen.setText("Verde (G)");

        btnAplicarCanais.setText("Aplicar canais ->");
        btnAplicarCanais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarCanaisActionPerformed(evt);
            }
        });

        jLabel3.setText("Entrada:");

        jLabel4.setText("Saida:");

        jMenu1.setText(" Arquivo");

        btnCarregarImagem.setText("Carregar imagem");
        btnCarregarImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarImagemActionPerformed(evt);
            }
        });
        jMenu1.add(btnCarregarImagem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(verImgInfo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelImgEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTrocarImgs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelImgSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(37, 37, 37)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbCanalRed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbCanalGreen)
                                .addGap(7, 7, 7)
                                .addComponent(cbCanalBlue))
                            .addComponent(comboEfeito, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAplicarEfeito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAplicarCanais))
                        .addGap(0, 347, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboEfeito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnAplicarEfeito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbCanalBlue)
                    .addComponent(cbCanalRed)
                    .addComponent(cbCanalGreen)
                    .addComponent(btnAplicarCanais))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelImgEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelImgSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnTrocarImgs, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(verImgInfo)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verImgInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verImgInfoActionPerformed
        if(imgTransformada == null) return;
        JOptionPane.showMessageDialog(this,
            "Largura x Altura: "+imgTransformada.getAltura()+" x "+imgTransformada.getLargura()+
                    "\nMédia de cinza: "+ imgTransformada.getMediaCinza()+
                    "\nVariancia de cinza: "+ imgTransformada.getVarianciaCinza()+
                    "\nMediana de cinza: "+ imgTransformada.getMedianaCinza()+
                    "\nModa de cinza: "+ imgTransformada.getModaCinza(),
            "Informações da imagem",
            JOptionPane.INFORMATION_MESSAGE);        // TODO add your handling code here:
    }//GEN-LAST:event_verImgInfoActionPerformed

    private void btnTrocarImgsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrocarImgsActionPerformed
        Imagem aux = imgEntrada;
        setImagemEntrada(imgTransformada);
        setImagemTransformada(aux);
    }//GEN-LAST:event_btnTrocarImgsActionPerformed

    private void btnAplicarEfeitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarEfeitoActionPerformed
        if(imgEntrada == null) return;
        switch(comboEfeito.getSelectedItem().toString().substring(0, 3)){
            case "ECZ":
                setImagemTransformada(imgEntrada.getTransformer(EscalaCinzaTransformer.class).transform());
                break;
            case "ICR":
                setImagemTransformada(imgEntrada.getTransformer(InverteCoresTransformer.class).transform());
                break;
        }
    }//GEN-LAST:event_btnAplicarEfeitoActionPerformed

    private void btnAplicarCanaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarCanaisActionPerformed
        if(imgEntrada == null) return;
        setImagemTransformada(imgEntrada.getTransformer(FiltraCanaisTransformer.class).
                transform(cbCanalRed.isSelected(), cbCanalGreen.isSelected(), cbCanalBlue.isSelected()));
    }//GEN-LAST:event_btnAplicarCanaisActionPerformed

    private void btnCarregarImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarImagemActionPerformed
        Imagem imagemEscolhida = Imagem.escolheImagem(); 
        if(imagemEscolhida == null) return;
        setImagemEntrada(imagemEscolhida);
    }//GEN-LAST:event_btnCarregarImagemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    public void setImagemEntrada(Imagem i) {
        this.imgEntrada = i;
        labelImgEntrada.setIcon(null);
        if(i != null)
            labelImgEntrada.setIcon(new ImageIcon(this.imgEntrada.getBuffered().
                    getScaledInstance(labelImgEntrada.getWidth(), labelImgEntrada.getHeight(),
                    Image.SCALE_SMOOTH)));
        
    }
    
    public void setImagemTransformada(Imagem i) {
        this.imgTransformada = i;
        labelImgSaida.setIcon(null);
        if(i != null)
            labelImgSaida.setIcon(new ImageIcon(this.imgTransformada.getBuffered().
                    getScaledInstance(labelImgSaida.getWidth(), labelImgSaida.getHeight(),
                    Image.SCALE_SMOOTH)));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicarCanais;
    private javax.swing.JButton btnAplicarEfeito;
    private javax.swing.JMenuItem btnCarregarImagem;
    private javax.swing.JButton btnTrocarImgs;
    private javax.swing.JCheckBox cbCanalBlue;
    private javax.swing.JCheckBox cbCanalGreen;
    private javax.swing.JCheckBox cbCanalRed;
    private javax.swing.JComboBox<String> comboEfeito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel labelImgEntrada;
    private javax.swing.JLabel labelImgSaida;
    private javax.swing.JButton verImgInfo;
    // End of variables declaration//GEN-END:variables
}
